<a href="https://colab.research.google.com/github/kavitha2509rohini/data-analytics-using-python/blob/main/day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
try:
    num = int(input("Enter Number:"))
    print(num)
except:
    print("invalid input")

Enter Number:55
55


In [ ]:
import numpy as np

mark = np.array([90, 85, 78, 98])
print(mark)

[90 85 78 98]


In [ ]:
import numpy as np

student = np.array([
    [90, 86],
    [88, 65],
    [44, 76]
])

print(student)

[[90 86]
 [88 65]
 [44 76]]


In [ ]:
import numpy as np
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
