<a href="https://colab.research.google.com/github/kavitha2509rohini/data-analytics-using-python/blob/main/day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
marks=np.array([80,90,77,66,89])
print(marks[1:4])

[90 77 66]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
new_arr=arr.reshape(2,3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
scores=[90,87,66,44,89]
total=sum(scores)
average=total/len(scores)
highest=max(scores)
lowest=min(scores)
print("Total score:", total)
print("Average score:", average)
print("highest score:", highest)
print("lowb score:", lowest)

Total score: 376
Average score: 75.2
highest score: 90
lowb score: 44


In [ ]:
sales = [1000, 2000, 30000, 4000]

total = sum(sales)
avg = total / len(sales)
high_sales = max(sales)
low_sales = min(sales)

print("Total:", total)
print("Average:", avg)
print("high_sales:", high_sales)
print("low_sales:", low_sales)

Total: 37000
Average: 9250.0
high_sales: 30000
low_sales: 1000


In [ ]:
import numpy as np
marks=np.array([70,89,77,90])
average=np.mean(marks)
print(average)

81.5


In [ ]:
import numpy as np
salary=np.array([10000,20000,30000,40000,50000,600000])
med=np.median(salary)
print(med)

35000.0
